### ISSUE TITLE
useSupabaseClient vs useSupabaseAuthClient?

### ISSUE THREAD

**Issue by franciscolourenco** [nuxt-modules/supabase#124]
What is the difference between these? They seem to return the same client with the same options?

**Comment by franciscolourenco** [comment]
I did dig through the code and it's still not completely clear what/why is happening with the session being shared between the server and frontend supabaseClients.

From the outside it is quite confusing that both composables are returning different instances of the supabaseClient, and the docs don't do a sufficient job at explaining why.

Would it be a possibility use [supabase.auth.setSession({refresh_token, access_token})](https://supabase.com/docs/reference/javascript/auth-setsession) instead of recreating the supabase client every time the access token changes? That way `useSupabaseAuthClient` could be deprecated.

**Comment by larbish** [comment]
Thank you for your feedback. I'v made the choice to create the `useSupabaseAuthClient` in order to fix the #114 issue while keeping client and server session/user synced. I'd be really pleased if you find a more appropriate way to handle it. Feel free to propose something in a PR, I'll be happy to review !
