### ISSUE TITLE
Is there a reason why the Session isn't set until the app is mounted?

### ISSUE THREAD

**Issue by Thexumaker** [nuxt-modules/supabase#161]
I was looking at `src/runtime/plugins/supabase.client.ts` and noticed that the session isn't set until after the app is mounted. This led to some issues if you're trying to make an API call that requires authentication after the created state but before the mounted state.
```
// Once Nuxt app is mounted
  nuxtApp.hooks.hook('app:mounted', () => {
    // Listen to Supabase auth changes
    authClient.auth.onAuthStateChange(async (event: AuthChangeEvent, session: Session | null) => {
      if (session) {
        await setServerSession(event, session)
        const userResponse = session ? await authClient.auth.getUser() : null
        user.value = userResponse ? userResponse.data.user : null
      } else {
        // User must be unset before session
        user.value = null
        await setServerSession(event, session)
      }
    })
  })
})
```

**Comment by larbish** [comment]
This is just a listener waiting for event on the Supabase session. Since supabase is communicating through browser (and not server) we need to wait for the mounted event to listen to it. The user is set on server side here: https://github.com/nuxt-modules/supabase/blob/main/src/runtime/plugins/supabase.server.ts#L18
