### ISSUE TITLE
Possible issue: useSupabaseClient() returns useSupabaseAuthClient

### ISSUE THREAD

**Issue by crewcall** [nuxt-modules/supabase#203]
While investigating a warning message I get in my app (_Multiple GoTrueClient instances detected in the same browser context._), I stumbled upon a line in [composables/useSupabaseClient.ts](https://github.com/nuxt-modules/supabase/blob/fe5b9e501a771f53f4a2972f5b8a39a2043591bf/src/runtime/composables/useSupabaseClient.ts#L19).

Shouldn't it be `return nuxtApp._supabaseClient as SupabaseClient<T>` instead?

https://github.com/nuxt-modules/supabase/blob/fe5b9e501a771f53f4a2972f5b8a39a2043591bf/src/runtime/composables/useSupabaseClient.ts#L19

Thanks for a short clarification and have a nice day!

**Comment by Aietes** [comment]
I'm getting the same warning, despite only using useSupabaseClient, and no AuthClient. I tried your suggested fix above, for me it doesn't seem to get rid of the warning though.

**Comment by zkschmitz** [comment]
I've got the same warning - curious if anyone knows the cause.

**Comment by Aietes** [comment]
`useSupabaseClient` is calling `createSupabaseClient()`at least twice on the server. The check `!nuxtApp._supabaseClient` always returns true. The attempt to store and retrieve the Supabase client instance via the `useNuxtApp()` might be problematic. The lifecycle of the Nuxt app instance may not correspond exactly to is expected. Depending on where and when this code is executed, a new Nuxt app instance might be created more often than expected, leading to the Supabase client being recreated each time.

One solution to this problem would be to use a module-level variable to store the Supabase client. This ensures that only one instance of the client is created for the lifetime of the module.

**Comment by Aietes** [comment]
We now implemented our own plugin to connect to Supabase, and have achieved a clean flow without errors. We do not require server-side authentication though, so the implementation is less sophisticated than the official module. We are never recreating the supabaseClient, but are rather using `supabase.auth.setSession` or `supabase.auth.getSession` to manage the session.

One important consideration came up in the process: We are using a PKCE flow, that is now available on all Supabase projects. It's more secure since auth tokens are not sent in the URL. It would be great if the module would adopt a PKCE flow by default. This should be fairly straightforward on the client, and setting cookies on the server for SSR is already implemented in the module anyway.

```ts
const supabase = createClient(
     'https://xyzcompany.supabase.co',
     'public-anon-key',
     options: {
       ...
       auth: {
         ...
         detectSessionInUrl: true,
         flowType: 'pkce',
       }
       ...
     }
)
```

**Comment by larbish** [comment]
This warning has been introduced by the last `gotrue` version. It might need a review of the client instantiation. We'll work on a new release including PKCE flow with @Aietes. We'll use this opportunity to fix this issue. Thanks for the mention.
