### ISSUE TITLE
Module @nuxtjs/supabase is disabled due to incompatibility issues

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-modules/supabase#71]
Hey, I removed the package-lock.json and the node_modules folder. I ran `npm i` and after that `npm run dev`. After that I got the warning ` WARN  Module @nuxtjs/supabase is disabled due to incompatibility issues:                                                             15:58:31
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9``

### Version
@nuxtjs/supabase: ex: v0.1.23
nuxt: 3.0.0-rc.9

**Comment by Gruce** [comment]
Hello @larbish, any update about the compatibility issue?

**Comment by Martijn91** [comment]
Hi, as a (temporary) workaround I just clone the @nuxtjs/supabase repo from git in my project's modules/ folder and install / dev:prepare / dev:build from the cloned module's root. Change the module import in your project's nuxt.config and you're good to go until fixes are being made, I've sensed it happened in multiple modules since rc9.

**Comment by Gruce** [comment]
Hello @Martijn91 Yes it works but it's not practical. 

Thank you

**Comment by larbish** [comment]
Hello there, should be fixed in [v0.1.25](https://github.com/nuxt-modules/supabase/releases/tag/v0.1.25) !

**Comment by mannyyang** [comment]
Could we merge these changes into the v2 branch as well?

**Comment by larbish** [comment]
@mannyyang Done, you can try version `0.2.0-15`
